[package]
name = "xashdb"
version = "0.1.0"
authors = ["TAKAMI Torao <koiroha@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
log4rs = "1"
thiserror = "1"
byteorder = "1"
highway = "0.6"
protobuf = "2"

[dev-dependencies]
tempfile = "3"
